# Generated by Django 2.2.8 on 2020-01-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='rubric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ads_rubric', to='ads.Rubric'),
        ),
    ]
