# Generated by Django 2.2.8 on 2020-01-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ads_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='rubric',
            field=models.ForeignKey(default=None, on_delete=False, related_name='ads_rubric', to='ads.Rubric'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='theme',
            field=models.ForeignKey(on_delete=False, related_name='ads_theme', to='ads.Theme'),
        ),
    ]
