# Generated by Django 2.2.8 on 2020-01-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200111_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique_for_date='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique_for_date='rubric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique_for_date='theme'),
            preserve_default=False,
        ),
    ]
