# Generated by Django 2.2.8 on 2020-01-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20200111_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='slug',
        ),
    ]
