# Generated by Django 2.2.8 on 2020-01-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_ads_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='slug',
        ),
    ]
