# Generated by Django 2.2.8 on 2020-01-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20200112_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='rubric',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ads_rubric', to='ads.Rubric'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_theme', to='ads.Theme'),
        ),
    ]
